### ISSUE TITLE
Folding of dependent cell

### ISSUE THREAD

**Issue by evgraph** [degivan/code-block-cells#3]
![image](https://user-images.githubusercontent.com/1563281/33778915-d3471ffe-dc5b-11e7-919d-adbebee5a05b.png)
![image](https://user-images.githubusercontent.com/1563281/33778936-e29e8d8e-dc5b-11e7-95ef-2c47fde5ef81.png)

**Comment by degivan** [comment]
I don't get it

**Comment by evgraph** [comment]
Here I expect that the text of dependent cells is folded, but it doesn't. Instead, I see the text of the previous cells and three dots after it.

**Comment by degivan** [comment]
Steps to reproduce are unclear. I was able to do it once, but after that it works just fine for me.
